language: python
dist: xenial

python:
  - 3.5
  - 3.6
  - 3.7
os:
  - linux
env:
  global:
    - PYTHON=python3
    - PIP=pip3

matrix:
  include:

    # macOS builds

    - language: generic
      python: 3.7
      os: osx

    # Linting

    - python: 3.7
      env: JOB=lint
      script: ${PYTHON} setup.py lint
      after_success: false

before_install:
  - set -e
  - |
    if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      shell_session_update() { :; }
      brew update
      brew unlink python@2
      brew upgrade python3
      cp test/scripts/sitecustomize.py .
    fi
install:
  - ${PIP} install codecov .[test]
script:
  - ${PYTHON} setup.py coverage -q
after_success:
  - codecov
