build: false
version: "{branch}-{build}"

environment:
  PYTHON_PATH: C:\Python2=37

install:
  - set PATH=%PYTHON_PATH%;%PYTHON_PATH%\Scripts;%PATH%
  - pip install codecov .[test]
test_script:
  - python setup.py coverage -q
on_success:
  - codecov
